[[plugins]]
repo = 'lambdalisue/vim-pyenv'
on_ft = ['python']

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = ['python']

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
on_ft = ['python']
depends = ['async.vim', 'vim-pyenv']
hook_add = '''
    let s:pyls_path = fnamemodify(g:python3_host_prog, ':h') . '/'. 'pyls'

    if (executable('pyls'))
        au User lsp_setup call lsp#register_server({
        \ 'name': 'pyls',
        \ 'cmd': {server_info->[expand(s:pyls_path)]},
        \ 'whitelist': ['python']
        \ })
    endif
'''

