[[snippets]]
  description = "show the ports which is listened"
  command = "lsof -i"
  output = ""

[[snippets]]
  description = "undos your last commit of git"
  command = "git reset --soft HEAD^"
  output = ""

[[snippets]]
  description = "check the running on screen"
  command = "screen -ls"
  output = ""

[[snippets]]
  description = "git add all"
  command = "git add -A"
  output = ""

[[snippets]]
  description = "git commit"
  command = "git commit -m \"\""
  output = ""

[[snippets]]
  description = "git push"
  command = "git push origin master"
  output = ""

[[snippets]]
  description = "restart network-manager"
  command = "sudo systemctl restart network-manager.service"
  output = ""
